// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)
type Comment struct {
	Email   string `json:"email"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type NewComment struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Content string `json:"content"`
	SongID  string `json:"songId"`
}

type NewSong struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Author   string `json:"author"`
	Category string `json:"category"`
}

type Song struct {
	ID       primitive.ObjectID `bson:"_id" json:"id"`
	Title    string     `json:"title"`
	Content  string     `json:"content"`
	Author   string     `json:"author"`
	Category string     `json:"category"`
	Comment  []*Comment `json:"comment"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
